name: greeting package  workflow
on:
   push:
      branches-ignore:
      - master
jobs:
   greeting_app:
      name: greeting app
      runs-on: ubuntu-latest
      steps:
      - name: getting copy of project.
        uses: actions/checkout@v2
      - name: setting up java environment.
        uses: actions/setup-java@v1
        with:
           java-version: 1.8
      - name: compiling project with mvn
        run: mvn compile
        shell: bash
      - name: packaging project with mvn
        if: success()
        run: mvn install
        shell: bash
